/marcsmobility.com/html/app/design/frontend/Theme/marcsmobility/Magento_Catalog/templates/product/price/final_price.phtml
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>

<?php if ($block->hasSpecialPrice()): ?>
    <?php //$save = $block->renderAmount($priceModel->getAmount()) - $block->renderAmount($finalPriceModel->getAmount()); ?>
	
	<?php //$save = $finalprice - $s_price; ?>
	
	<span class="old-price prc">
		<span class="price-label view-detail-label">Regular Price<span class="collon">:</span> </span>
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            //'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
	
	<span class="special-price">
			<span class="price-label view-detail-label">Sale Price<span class="collon">:</span> </span>
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            //'display_label'     => __('Sale Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
		<span class="you-save">( You Save $6.00 )</span>
    </span>
	
<?php else: ?>
	
	<span class="price-label view-detail-label">Sale Price<span class="collon">:</span> </span>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
	
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </span>
    <?php endif?>
<?php endif; ?>
<script language="JavaScript" type="Text/Javascript">
require([
    "jquery"
], function($){
//<![CDATA[
    $(document).ready(function() {
		var pid = '<?php echo $productId ?>';
		var special = $('#product-price-'+pid).text();
var reguler = $('#old-price-'+pid).text();
		if(reguler != ""){
 
var ss = special.replace( /^\D+/g, ''); ;
var rr = reguler.replace( /^\D+/g, ''); ;
var save = rr.replace(",","") - ss.replace(",","");


$('.you-save').replaceWith('<span class="you-save"> (You Save $'+ save  +'.00 )</span>');
		}
	});
//]]>
});	
</script>